baseURL = 'https://francofierro.github.io/'
languageCode = 'en-us'
title = 'Franco Fierro 🥑'
theme = 'PaperMod'
enableEmoji = true

[params]
    defaultTheme = 'auto'
    disableThemeToggle = true

[params.author]
    name = 'Franco Fierro'

[[params.socialIcons]]
    name = 'linkedin'
    url = 'https://www.linkedin.com/in/franco-neud%C3%B6rfer-305783404/'

[menu]
    [[menu.main]]
    name = 'Posts'
    url = '/posts/'

