baseURL = 'https://francofierro.github.io/'
languageCode = 'en-us'
title = 'Franco Fierro'
theme = 'PaperMod'
enableEmoji = true
copyright = '© 2025 Franco Fierro'
[params.homeInfoParams]
Title = "Hi there :wave:"
Content = "Here are my blog posts"

