baseURL = 'https://francofierro.github.io/'
languageCode = 'en-us'
title = 'Franco Fierro 🥑'
theme = 'PaperMod'
enableEmoji = true
copyright = '© 2025 Franco Fierro'

[params]
    defaultTheme = 'auto'
    disableThemeToggle = true

[menu]
    [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    [[menu.main]]
    name = 'About'
    url = ''

